booktime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('localusers.urls'))
]

localusers/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from localusers import forms

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name="localusers/login.html",
         form_class=forms.AuthenticationForm,), name='login'),
    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(),
         name='address_update'),
    path('address/<int:pk>/delete',
         views.AddressDeleteView.as_view(), name='address_delete')
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView, DetailView
from .views import ContactFormView, ProductListView, add_to_basket, manage_basket, AddressSelectionView
from main import models
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", TemplateView.as_view(template_name="main/home.html"), name='home'),
    path("about/", TemplateView.as_view(template_name="main/about.html"), name='about'),
    path("contact/", ContactFormView.as_view(), name='contact'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='products'),
    path('product/<slug:slug>/',
         DetailView.as_view(model=models.Product), name='product'),
    path('add_to_bascket/', add_to_basket, name='add_to_basket'),
    path('basket/', manage_basket, name="basket"),
    path('order/done', TemplateView.as_view(template_name='main/order_done.html'),
         name="checkout_done"),
    path('order/address_select/',
         AddressSelectionView.as_view(), name='address_select')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

localusers/models.py
from django.db import models
# AbstratUser is for creating a new User while the BaseUserManager is for creating a manager
from django.contrib.auth.models import AbstractUser, BaseUserManager
# Create your models here.


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('SuperUser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ('ke', 'Kenya')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField("Address line 2", max_length=60, blank=True)
    zip_code = models.CharField("ZIP / Postal code", max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTRIES)

    def __str__(self):
        return ", ".join([self.name, self.address1, self.address2, self.zip_code, self.city, self.country])

localusers/forms.py
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UsernameField
from . import models
from django.core.mail import send_mail
from django.contrib.auth import authenticate
import logging
from django import forms


logger = logging.getLogger(__name__)

# Django 2.0 release, the inner Meta class needs to be overridden when there is a custom User model. Django 2.1 will change that.


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(f'Sending signup email for {self.cleaned_data["email"]}')
        message = f"Welcome {self.cleaned_data['email']}"
        send_mail(
            'Welcome to BookTime',
            message,
            'site@booktime.domain',
            [self.cleaned_data["email"]],
            fail_silently=True
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(
                self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination.")
            logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data

    def get_user(self):
        return self.user

localusers/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
import logging
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserCreationForm
from . import models


# Create your views here.


logger = logging.getLogger(__name__)


class SignUpView(FormView):
    template_name = 'localusers/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        response = super().form_invalid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        logger.info(f'New Signup for email {email}')
        user = authenticate(email=email, password=raw_password)
        login(self.request, user)
        form.send_mail()
        messages.info(self.request, 'You have signup successfully')
        return response

# Giving customers the ability to change and delete there addresses
# We are going to use  these class-based views: ListView, CreateView, UpdateView, and DeleteView.
# The LoginRequieredMixin is used to make sure the this views are only seen when logged in


class AddressListView(LoginRequiredMixin, ListView):
    model = models.Address

    def get_queryset(self):
        # only getting the address belonging to the customer
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = models.Address
    fields = ['name', 'address1', 'address2', 'zip_code', 'city', 'country']
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Address
    fields = ['name', 'address1', 'address2', 'zip_code', 'city', 'country']
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

localusers/templates/localusers/address_form.html
{% extends "../base.html" %} {% block content %}
<h2>Add a new address</h2>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

localusers/templates/localusers/address_list.html
{% extends "../base.html" %}

{% block content %}
<h1>List of your addresses:</h1>
{% for address in object_list %}
<p>
    {{ address.name }}<br>
    {{ address.address1 }}<br>
    {{ address.address2 }}<br>
    {{ address.city }}<br>
    {{ address.get_country_display }}<br>
</p>
<p>
    <a href="{% url "address_update" address.id %}">Update Address</a>
</p>
<p>
    <a href="{% url "address_delete" address.id %}">Delete Address </a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<p>
    <a href="{% url "address_create" %}">Add new address</a>
</p>
{% endblock %}

localusers/templates/localusers/address_select.html
{% extends "../base.html" %} {% block content %}
<h2>Select the billing/shipping addresses</h2>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
  <a class="btn btn-primary" href='{% url "address_create"%}'>Add a new one</a>
</form>
{% endblock %}

localusers/templates/localusers/address_update.html
{% extends "../base.html" %} {% block content %}
<h2>Update Address</h2>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

localusers/templates/localusers/confirm_delete.html
{% extends "../base.html" %} {% block content %}
<h2>Delete Address</h2>
<form method="POST">
  {% csrf_token %}
  <p>Are you sure you want to delete it?</p>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

localusers/templates/localusers/login.html
{% extends "../base.html" %} {% block content %}
<div class="card mx-auto mt-5" style="width:30rem; padding:30px;">
<h2 class="my-3">Login</h2>
<p>Please fill the form below.</p>
<form method="POST"  >
  {% csrf_token %}
  {{ form.non_field_errors }}
  <!--###############-email-##############-->
  <div class="form-group my-3">
    {{ form.email.label_tag }}
    <input
      type="email"
      class="form-control {% if form.email.errors %} is-invalid {% endif %}"
      name="email"
      id="id_email"
      placeholder="Your email"
      value="{{ form.email.value|default:'' }}"
    />
    {% if form.email.errors %}
    <div class="invalid-feedback">{{ form.email.errors }}</div>
    {% endif %}
  </div>
  <!--###############-end-email-##############-->
  <!--###############-password-2-##############-->
  <div class="form-group  my-3">
    {{ form.password.label_tag }}
    <input
     type="password" 
    class="form-control {% if form.password2.errors %}is-invalid{% endif %}" 
    name="password"
    id="id_password" 
    value="{{ form.password.value|default:'' }}" >
     {% if form.password.errors %}
    <div class="invalid-feedback">{{ form.password.errors }}</div>
    {% endif %}
  </div>
  <!--###############-end-password2-##############-->

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form>
</div>
{% endblock %}

localusers/templates/localusers/signup.html
{% extends "../base.html" %} {% block content %}
<div class="card mx-auto mt-5" style="width:30rem; padding:30px;">
<h2 class="my-3">Sign up</h2>
<p>Please fill the form below.</p>
<form method="POST"  >
  {% csrf_token %}
  <!--###############-email-##############-->
  <div class="form-group my-3">
    {{ form.email.label_tag }}
    <input
      type="email"
      class="form-control {% if form.email.errors %} is-invalid {% endif %}"
      name="email"
      id="id_email"
      placeholder="Your email"
      value="{{ form.email.value|default:'' }}"
    />
    {% if form.email.errors %}
    <div class="invalid-feedback">{{ form.email.errors }}</div>
    {% endif %}
  </div>
  <!--###############-end-email-##############-->
  <!--###############-password-1-##############-->
  <div class="form-group  my-3">
    {{ form.password1.label_tag }}
    <input
      type="password"
      class="form-control {% if form.password1.errors %}is-invalid{% endif %}"
      name="password1"
      id="id_password1"
      value="{{ form.password1.value|default:'' }}"
    />
    {% if form.password1.errors %}
    <div class="invalid-feedback">{{ form.password1.errors }}</div>
    {% endif %}
  </div>
  <!--###############-end-password-1-##############-->
  <!--###############-password-2-##############-->
  <div class="form-group  my-3">
    {{ form.password2.label_tag }}
    <input
     type="password" 
    class="form-control {% if form.password2.errors %}is-invalid{% endif %}" 
    name="password2"
    id="id_password2" 
    value="{{ form.password2.value|default:'' }}" >
     {% if form.password2.errors %}
    <div class="invalid-feedback">{{ form.password2.errors }}</div>
    {% endif %}
  </div>
  <!--###############-end-password2-##############-->

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</form>
</div>
{% endblock %}