booktime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('localusers.urls'))
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView, DetailView
from .views import ContactFormView, ProductListView, add_to_basket, manage_basket, AddressSelectionView
from main import models
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", TemplateView.as_view(template_name="main/home.html"), name='home'),
    path("about/", TemplateView.as_view(template_name="main/about.html"), name='about'),
    path("contact/", ContactFormView.as_view(), name='contact'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='products'),
    path('product/<slug:slug>/',
         DetailView.as_view(model=models.Product), name='product'),
    path('add_to_bascket/', add_to_basket, name='add_to_basket'),
    path('basket/', manage_basket, name="basket"),
    path('order/done', TemplateView.as_view(template_name='main/order_done.html'),
         name="checkout_done"),
    path('order/address_select/',
         AddressSelectionView.as_view(), name='address_select')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model
import logging
from . import exceptions


# Create your models here.

User = get_user_model()
logger = logging.getLogger(__name__)


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('ProductTag', blank=True)

    # This method will be availProduct.objects.active() to return only active products. To finish this
    objects = ActiveManager()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    # The product stores the primary key of the linked product model.It is used by the ORM to run JOIN operations automatically when accessed
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to='product-thumbnails', null=True)

    def __self__(self):
        return self.product.name


class ProductTag(models.Model):
    # One product may have one or many tags, and one tag may contain one or more products
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise exceptions.BasketException(
                "Cannot create order without user"
            )

        logger.info(
            "Creating order for basket_id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )

        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
        order = Order.objects.create(**order_data)
        c = 0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order": order,
                    "product": line.product,
                }
                order_line = OrderLine.objects.create(
                    **order_line_data
                )
                c += 1

        logger.info(
            "Created order with id=%d and lines_count=%d",
            order.id,
            c,
        )

        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(
        default=1, validators=[MinValueValidator(1)])


class Order(models.Model):
    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)

    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(
        max_length=60, blank=True
    )
    billing_zip_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)

    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(
        max_length=60, blank=True
    )
    shipping_zip_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled"),
    )

    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="lines"
    )
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT
    )
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging
from django.forms import inlineformset_factory
from . import models
from . import widgets
from localusers.models import Address

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name ', max_length=100, required=True)
    message = forms.CharField(
        max_length=600, widget=forms.Textarea, required=True)

    def send_mail(self):
        logger.info('Sending email to customer service')
        message = f"From:{self.cleaned_data['name']}, Message: {self.cleaned_data['message']}"
        send_mail(
            'Site Message',
            message,
            'site@booktime.domain',
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )


BasketLineFormSet = inlineformset_factory(
    models.Basket,
    models.BasketLine,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None)
    shipping_address = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(). __init__(*args, **kwargs)
        queryset = Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset

main/views.py
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import ContactForm, BasketLineFormSet, AddressSelectionForm
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from main import models

# Create your views here.


class ProductListView(ListView):
    template_name = 'main/products_list.html'
    paginate_by = 4

    # we return the products filtered by active then by tag if the tag is specified and if not return all the active products
    # When an instance of this view is created, the attributes args and kwargs are populated with information from the URL route. In our case,
    # this view is expecting to be called with the tag specified in the URL path, rather than in a GET parameter. If, on the other hand, the tag were a GET
    # parameter, it could be accessed using the self.request.GET dictionary.
    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != 'all':
            self.tag = get_object_or_404(models.ProductTag, slug=tag)
        if self.tag:
            products = models.Product.objects.active().filter(tags=self.tag)
        else:
            products = models.Product.objects.active()
        return products.order_by('name')


class ContactFormView(FormView):
    template_name = 'main/contact.html'
    form_class = ContactForm
    success_url = '/'

# This function is callled if the form is valid
    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


def add_to_basket(request):
    product = get_object_or_404(
        models.Product, pk=request.GET.get("product_id"))
    basket = request.basket
    if not request.basket:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        basket = models.Basket.objects.create(user=user)
        request.session["basket_id"] = basket.id
    basketline, created = models.BasketLine.objects.get_or_create(
        basket=basket, product=product)
    if not created:
        basketline.quantity += 1
        basketline.save()
    return HttpResponseRedirect(reverse("product", args=(product.slug,)))


def manage_basket(request):
    if not request.basket:
        return render(request, "main/basket.html", {"formset": None})
    if request.method == "POST":
        formset = BasketLineFormSet(request.POST, instance=request.basket)
        if formset.is_valid():
            formset.save()
    else:
        formset = BasketLineFormSet(instance=request.basket)
    if request.basket.is_empty():
        return render(request, "main/basket.html", {"formset": None})
    return render(request, "main/basket.html", {"formset": formset})


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = "localusers/address_select.html"
    form_class = AddressSelectionForm
    success_url = reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['basket_id']
        basket = self.request.basket
        basket.create_order(
            form.cleaned_data['billing_address'],
            form.cleaned_data['shipping_address']
        )
        return super().form_valid(form)

main/templates/main/about.html
{% extends "../base.html" %} {% block content%}
<h1>Hello World</h1>
<p>About Us</p>
{% endblock%}

main/templates/main/basket.html
{% extends "../base.html" %} {% block content %}
<h2>Basket</h2>
{% if formset %}
<p>You can adjust the quantities below.</p>
<form method="POST">
  {% csrf_token %} {{ formset.management_form }} {% for form in formset %}
  <p>{{ form.instance.product.name }} {{ form }}</p>
  {% endfor%}
  <button type="submit" class="btn btn-success">Update Basket</button>
  {% if user.is_authenticated %}
  <a href="{% url 'address_select' %}" class="btn btn-primary">Place Order</a>
  {% else%}
  <a
    class="btn btn-primary"
    href="{% url 'signup' %}?next={% url 'address_select' %}"
    >SignUp</a
  >
  <a
    href="{% url 'login' %}?next={% url 'address_select' %}"
    class="btn btn-primary"
    >Login</a
  >
  {% endif %}
</form>
{% else %}
<p>You have no items in the basket.</p>
{% endif %} {% endblock %} {% block js %} {% if formset %} {{ formset.media }}
{% endif%} {% endblock%}

main/templates/main/contact.html
{% extends "../base.html" %} {% block content%}
<div class="container mt-5 card px-5 py-5" style="width: 500px">
  <h2 class="mb-4">Contact Form</h2>
  <form method="POST">
    {% csrf_token %}

    <div class="form-group">
      {{ form.name.label_tag }}
      <input
        type="text"
        class="form-control mt-2 mb-4 {% if form.name.errors %} is-invalid {% endif %}"
        id="id_name"
        name="name"
        placeholder="Your name"
        value="{{ form.name.value | default:'' }}"
      />
      {% if form.name.errors %} {% for message in form.name.errors %}
      <div class="alert alert-danger" role="alert">{{message }}</div>

      {% endfor %} {% endif %}
    </div>

    <div class="form-group">
      {{ form.message.label_tag }}
      <textarea
        class="form-control mt-2 mb-4 {% if form.message.errors %} is-invalid {% endif %}"
        id="id_message"
        name="message"
        row="3"
      >
    {{ form.message.value|default:''}} 
</textarea
      >
      {% if form.message.errors %} {% for message in form.message.errors %}
      <div class="alert alert-danger" role="alert">{{message }}</div>

      {% endfor %} {% endif %}
    </div>
    <button type="submit" class="btn btn-primary my-3">Submit</button>
  </form>
</div>
{% endblock%}

main/templates/main/home.html
{% extends "../base.html" %} {% block content%}
<h1>Hello World</h1>
<p>Home Page</p>
{% endblock%}

main/templates/main/order_done.html
{% extends "base.html" %} {% block content %}
<p>Thanks for your order.</p>
{% endblock %}

main/templates/main/product_detail.html
{% extends "../base.html" %} {% block content %}
<h1 class="my-3">Product</h1>
<table class="table">
  <tr>
    <th>Name</th>
    <td>{{ object.name }}</td>
  </tr>
  <tr>
    <th>Cover images</th>
    <td>
      {% for image in object.productimage_set.all %}
      <img src="{{ image.thumbnail.url }}" alt="cover" />
      {% endfor %}
    </td>
  </tr>
  <tr>
    <th>Price</th>
    <td>{{ object.price }}</td>
  </tr>
  <tr>
    <th>Description</th>
    <td>{{ object.description|linebreaks }}</td>
  </tr>
  <tr>
    <th>Tags</th>
    <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
  </tr>
  <tr>
    <th>In stock</th>
    <td>{{ object.in_stock|yesno|capfirst }}</td>
  </tr>
  <tr>
    <th>Updated</th>
    <td>{{ object.date_updated|date:"F Y" }}</td>
  </tr>
</table>
<a href="{% url "add_to_basket" %}?product_id={{ object.id }}">Add To Bascket</a>
{% endblock content %}

main/templates/main/products_list.html
{% extends "../base.html" %}

{% block content %}
  <h1 class="my-3">Products</h1>
  {% for product in page_obj %}
    <p>{{ product.name }}</p>
    <p>
      <a href="{% url "product" product.slug %}">See it here</a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  <!--###################-Pagnation-######################-->
  <nav class="mt-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{page_obj.previous_page_number}}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Previous</a>
        </li>
      {% endif %}
      {% for pagenum in page_obj.paginator.page_range %}
        <li
          class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
          <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
      {% endif %}
    </ul>
  </nav>
<!--###################-End Pagnation-######################-->

{% endblock content %}